### ISSUE TITLE
Qadim logs failing to parse (Log incomplete)

### ISSUE THREAD

**Issue by Sejsel** [baaron4/GW2-Elite-Insights-Parser#504]
Found some Qadim logs that result in an exception. Seems to be the case for fairly short logs that are not incomplete, they properly end. Can this please be handled gracefully and not with an fatal exception? 

Found when comparing results with https://github.com/gw2scratch/evtc/.

```
Exception: GW2EIEvtcParser.Exceptions.IncompleteLogException: Log incomplete
   at GW2EIEvtcParser.EncounterLogic.Qadim.GetFightOffset(FightData fightData, AgentData agentData, List`1 combatData) in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EI/GW2EIEvtcParser/EncounterLogic/Raids/W6/Qadim.cs:line 165
   at GW2EIEvtcParser.EvtcParser.OffsetEvtcData() in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EI/GW2EIEvtcParser/EvtcParser.cs:line 731
   at GW2EIEvtcParser.EvtcParser.PreProcessEvtcData() in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EI/GW2EIEvtcParser/EvtcParser.cs:line 748
   at GW2EIEvtcParser.EvtcParser.ParseLog(ParserController operation, Stream stream) in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EI/GW2EIEvtcParser/EvtcParser.cs:line 105
   at GW2EIEvtcParser.EvtcParser.ParseLog(ParserController operation, FileInfo evtc) in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EI/GW2EIEvtcParser/EvtcParser.cs:line 78
```

[20190312-174928.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/5632361/20190312-174928.evtc.zip)
[20190412-020219.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/5632362/20190412-020219.evtc.zip)

I have a LOT more of these if needed.

**Comment by EliphasNUIT** [comment]
That part of the code is to adjust the start time to match the encounter timer start. I guess it's not important to not let through logs where that event is not present. Their content won't be very valuable to begin with.

Removed in 5784944573480b00ee4edf3dd2137def930f8d8e.
