### ISSUE TITLE
Conjured Amalgamate NPE

### ISSUE THREAD

**Issue by Sejsel** [baaron4/GW2-Elite-Insights-Parser#508]
EI Version: e0581fe4c0e4a55d1c6ffb876e62a4247b9fd44f.

Found when comparing results with https://github.com/gw2scratch/evtc/.

```
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GW2EIEvtcParser.EncounterLogic.ConjuredAmalgamate.CheckSuccess(CombatData combatData, AgentData agentData, FightData fightData, HashSet`1 playerAgents) in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EI/GW2EIEvtcParser/EncounterLogic/Raids/W6/ConjuredAmalgamate.cs:line 195
   at GW2EIEvtcParser.ParsedEvtcLog..ctor(String buildVersion, FightData fightData, AgentData agentData, SkillData skillData, List`1 combatItems, List`1 playerList, Int64 evtcLogDuration, EvtcParserSettings parserSettings, ParserController operation) in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EI/GW2EIEvtcParser/ParsedEvtcLog.cs:line 53
   at GW2EIEvtcParser.EvtcParser.ParseLog(ParserController operation, FileInfo evtc) in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EI/GW2EIEvtcParser/EvtcParser.cs:line 89
   at GW2Scratch.EVTCAnalytics.LogTests.EliteInsights.EliteInsightsLogChecker.CheckLog(String filename) in /home/sejsel/programming/projects/current/gw2/ScratchEVTCParser/EVTCAnalytics.LogTests.EliteInsights/DefinitionLogChecker.cs:line 76
```

[20180928-202845.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/5642487/20180928-202845.evtc.zip)
[20181212-034242.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/5642491/20181212-034242.evtc.zip)

**Comment by EliphasNUIT** [comment]
Fixed in 58e342b6a8152fd8c631abff315bfd290b2df2bb.

Thanks.
