### ISSUE TITLE
CLI crash on linux with missing ~/.local/share directory

### ISSUE THREAD

**Issue by rigel314** [baaron4/GW2-Elite-Insights-Parser#939]
**Describe the bug**
Attempting to run the CLI build on linux with the dotnet 8 runtime, crashes unless you manually create a folder at ~/.local/share

**To Reproduce**
1. Create a new linux user (or otherwise avoid having a ~/.local/share folder)
2. `wget https://github.com/baaron4/GW2-Elite-Insights-Parser/releases/download/v3.0.0.0/GW2EICLI.zip`
3. `unzip GW2EICLI.zip`
4. `dotnet ./GuildWars2EliteInsights-CLI.dll`
5. See error 
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Directory.GetParent(String path)
   at System.Configuration.LocalFileSettingsProvider.GetPreviousConfigFileName(Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at GW2EIParser.Program.Main(String[] args) in G:\Projects\GW2-Elite-Insights-Parser\GW2EIParserCLI\Program.cs:line 20
[1]    539975 abort (core dumped)  dotnet ./GuildWars2EliteInsights-CLI.dll
```
6. `mkdir -p ~/.local/share`
7. `mkdir -p ~/.config`
8. `dotnet ./GuildWars2EliteInsights-CLI.dll`
9. See expected functionality
```
dotnet [arguments] [logs...]

-c [config path] : use another config file
-h : help
```

From the stack trace, I found this issue on the dotnet project: https://github.com/dotnet/runtime/issues/98715, which gives a workaround of creating the folder.  (along with ~/.config)

Since it's pretty clearly an upstream issue, I'm mostly creating this issue in case anyone here runs into the same issue trying to use Elite Insights CLI.

**Comment by stellarashes** [comment]
I ran into the same issue trying to put this inside a container, and ended up finding the same issue on dotnet. Wish I saw your post earlier.
